export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const CHANGE_POSITION = 'CHANGE_POSITION';
export const ON_EDITING = 'ON_EDITING';